AllCops:
  Includes:
    - config/routes.rb
    - app/models/*
  Excludes:
    - db/**
    #- config/**/*
    - script/**
    - vendor/**/*
    - tmp/**
    - test/**
    - storage/**/*
    - public/*
    - lib/**
    - bin/**

Metrics/LineLength:
  Max: 100

Layout/IndentationWidth:
  Width: 2

Style/FrozenStringLiteralComment:
  Enabled: false